name: PR Review

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/pr-review@main
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          approve_comment: |
            HI @${{ github.event.pull_request.user.login }}, approve
