name: PR Review

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/pr-approve@main
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          comment: |
            HI @${{ github.event.pull_request.user.login }}, approve

      - uses: actions-cool/pr-review@main
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          type: COMMENT
          position: 4
          path: README.md
          comment: |
            HI @${{ github.event.pull_request.user.login }}, comment

      - uses: actions-cool/pr-review@main
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          type: REQUEST_CHANGES
          path: README.md
          position: 4
          comment: |
            HI @${{ github.event.pull_request.user.login }}, request_changes
